version: '3.7'
services:
  dhos-hapi-fhir-api:
    build: .
    container_name: dhos-hapi-fhir-api
    restart: on-failure
    ports:
    - 8080:8080
    environment:
      spring.datasource.url: jdbc:postgresql://host.docker.internal:5432/dhos-hapi-fhir-api
      spring.datasource.username: dhos-hapi-fhir-api
      spring.datasource.password: dhos-hapi-fhir-api
      spring.datasource.driverClassName: org.postgresql.Driver
      spring.datasource.max-active: 15

      hapi.fhir.server_address: http://localhost:8080/fhir

      # web ui
      hapi.fhir.tester.home.name: Local Tester
      hapi.fhir.tester.home.server_address: http://host.docker.internal:8080/fhir
      hapi.fhir.tester.home.fhir_version: R4

      # custom auth
      hapi.fhir.server_client_id: SensyneHealth
      hapi.fhir.server_client_secret: UnbelievablyHardPassword123qwerty
